# Generated by Django 2.0.5 on 2018-12-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='examPatrak',
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
