# Generated by Django 2.0.5 on 2018-12-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('Exam', '0002_auto_20181204_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examPatrak', models.FileField(blank=True, max_length=50, null=True, upload_to='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.AddField(
            model_name='examcourse',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.Exam'),
        ),
    ]
