# Generated by Django 2.0.5 on 2018-12-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_auto_20181206_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='Course.Course'),
        ),
        migrations.AlterField(
            model_name='examcourse',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Exam.Exam'),
        ),
    ]
