# Generated by Django 2.0.5 on 2018-12-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_auto_20181210_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Course.Course'),
        ),
        migrations.AlterField(
            model_name='examcourse',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='Exam.Exam'),
        ),
    ]
