# Generated by Django 2.1.5 on 2019-01-27 05:23

import Students.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(blank=True, max_length=100, null=True)),
                ('countrySortName', models.CharField(blank=True, max_length=20, null=True)),
                ('countryPhoneCOde', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('ISO', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.FileField(blank=True, upload_to=Students.models.user_directory_path)),
                ('fatherName', models.CharField(blank=True, max_length=50, null=True, verbose_name='fatherName')),
                ('motherName', models.CharField(blank=True, max_length=50, null=True, verbose_name='motherName')),
                ('rollNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='rollNumber')),
                ('enrollmentNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='enrollmentNumber')),
                ('scholarshipNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='scholarshipNumber')),
                ('adhaarNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='adhaarNumber')),
                ('familyId', models.CharField(blank=True, max_length=50, null=True, verbose_name='familyId')),
                ('sssmId', models.CharField(blank=True, max_length=50, null=True, verbose_name='sssmId')),
                ('bankName', models.CharField(blank=True, max_length=50, null=True, verbose_name='bankName')),
                ('bankIfsc', models.CharField(blank=True, max_length=50, null=True, verbose_name='bankIfsc')),
                ('accountNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='accountNumber')),
                ('mobileNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='mobileNumber')),
                ('gender', models.IntegerField(default=0, verbose_name='gender')),
                ('medium', models.IntegerField(default=0, verbose_name='medium')),
                ('dateOfBirth', models.DateField(blank=True, max_length=50, null=True, verbose_name='dateOfBirth')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('postalCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='postalCode')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.Countries')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Course.Course')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.States')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.States'),
        ),
    ]
