# Generated by Django 2.0.5 on 2019-04-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=10, null=True)),
                ('examSubject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='Subject.ExamSubject')),
            ],
        ),
    ]
