# Generated by Django 2.0.5 on 2019-01-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0003_auto_20181210_1728'),
        ('ExamMarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionexammarks',
            name='sessionExam',
        ),
        migrations.AddField(
            model_name='sessionexammarks',
            name='examSubject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='Subject.ExamSubject'),
        ),
        migrations.AlterField(
            model_name='sessionexammarks',
            name='sessionStudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markstudent', to='SessionYear.SessionCourseExamStudents'),
        ),
    ]
