# Generated by Django 2.0.5 on 2019-04-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SessionYear', '0001_initial'),
        ('ExamMarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexammarks',
            name='sessionStudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markstudent', to='SessionYear.SessionCourseExamStudents'),
        ),
    ]
