# Generated by Django 2.0.5 on 2019-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='isGrade',
            field=models.IntegerField(default=False),
        ),
    ]
