# Generated by Django 2.0.5 on 2018-12-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subject', '0002_auto_20181206_1707'),
        ('Exam', '0003_auto_20181206_1518'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=10, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sessionStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Students')),
            ],
        ),
        migrations.CreateModel(
            name='SessionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionStartDate', models.DateField(null=True)),
                ('sessionEndDate', models.DateField(null=True)),
                ('sessionDescription', models.CharField(max_length=250, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('courseExam', models.ManyToManyField(to='Exam.ExamCourse')),
                ('courseExamSubject', models.ManyToManyField(to='Subject.ExamSubject')),
                ('students', models.ManyToManyField(to='Students.Students')),
            ],
        ),
    ]
