# Generated by Django 2.0.5 on 2018-12-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
        ('Exam', '0003_auto_20181206_1518'),
        ('Subject', '0002_auto_20181206_1707'),
        ('SessionYear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCourseExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseExam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.ExamCourse')),
                ('courseExamSubject', models.ManyToManyField(to='Subject.ExamSubject')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionyear',
            name='courseExam',
        ),
        migrations.RemoveField(
            model_name='sessionyear',
            name='courseExamSubject',
        ),
        migrations.RemoveField(
            model_name='sessionyear',
            name='students',
        ),
        migrations.AlterField(
            model_name='sessionyear',
            name='sessionDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sessioncourseexam',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SessionYear.SessionYear'),
        ),
        migrations.AddField(
            model_name='sessioncourseexam',
            name='students',
            field=models.ManyToManyField(to='Students.Students'),
        ),
    ]
