# Generated by Django 2.1.5 on 2019-01-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SessionYear', '0001_initial'),
        ('Exam', '0001_initial'),
        ('Subject', '0001_initial'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncourseexamstudents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='Students.Students'),
        ),
        migrations.AddField(
            model_name='sessioncourseexam',
            name='courseExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseExam', to='Exam.ExamCourse'),
        ),
        migrations.AddField(
            model_name='sessioncourseexam',
            name='courseExamSubject',
            field=models.ManyToManyField(related_name='sessionsubject', to='Subject.ExamSubject'),
        ),
        migrations.AddField(
            model_name='sessioncourseexam',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='SessionYear.SessionYear'),
        ),
    ]
