# Generated by Django 2.0.5 on 2019-04-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('SessionYear', '0002_auto_20190406_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncourseexam',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sessioncourse', to='Course.Course'),
            preserve_default=False,
        ),
    ]
