# Generated by Django 2.0.5 on 2018-12-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SessionYear', '0002_auto_20181206_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncourseexam',
            name='courseExam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='Exam.ExamCourse'),
        ),
        migrations.AlterField(
            model_name='sessioncourseexam',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='SessionYear.SessionYear'),
        ),
    ]
