# Generated by Django 2.0.5 on 2018-12-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20181210_1808'),
        ('SessionYear', '0004_auto_20181206_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCourseExamStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(null=True)),
                ('result', models.CharField(max_length=250, null=True)),
                ('rank', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sessioncourseexam',
            name='students',
        ),
        migrations.AddField(
            model_name='sessioncourseexamstudents',
            name='courseexam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseexam', to='SessionYear.SessionCourseExam'),
        ),
        migrations.AddField(
            model_name='sessioncourseexamstudents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='Students.Students'),
        ),
    ]
