# Generated by Django 2.0.5 on 2018-12-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionYear', '0006_auto_20181220_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioncourseexam',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
